### ISSUE TITLE
Correlation between attributes and dealing with missing values

### ISSUE THREAD

**Issue by sreedharjinka** [sreedharjinka/Thyroid-DetectionG97#5]

**Comment by iAm-Abhiram7** [comment]
# Exploratory data analysis

- used to analyze and investigate data sets and summarize their main characteristics , mainly used to discover patterns , spot anomalies 
- convert T to 0 and F to 1 and replace all ?s with NaN
- make a list of features that have missing values
- finding out the % of missing values present in the dataset

[corrANDmissingVal.txt](https://github.com/sreedharjinka/Thyroid-DetectionG97/files/13238027/corrANDmissingVal.txt)

- plotting a basic boxplot to understand the dynamic of the data we are dealing with 


--OUTPUT
![Screenshot (19)](https://github.com/sreedharjinka/Thyroid-DetectionG97/assets/147491619/430d7173-895d-4af4-92d4-187d7ba962c6)

''' these are the attributes that have missing values that were filled with NaN ['gender', 'TSH', 'T3', 'TT4', 'FTI'] and the percentage of missing values are 
gender 0.0021 % missing values
TSH 0.0336 % missing values
T3 0.1587 % missing values
TT4 0.0079 % missing values
FTI 0.0322 % missing values'''
