### ISSUE TITLE
Plot and Verify the Dataset using Gaussian Distribution

### ISSUE THREAD

**Issue by sreedharjinka** [sreedharjinka/Thyroid-DetectionG97#7]

**Comment by SIVAMANI-PVN** [comment]
Done with analysing gaussian and normal distribution
![Screenshot (49)](https://github.com/sreedharjinka/Thyroid-DetectionG97/assets/147395657/3fe01c12-ba2b-4093-9753-71a87c623e11)
![Screenshot (50)](https://github.com/sreedharjinka/Thyroid-DetectionG97/assets/147395657/79ce5a4f-28d5-48ec-809e-d6970a3e1df9)
[2-11-23.txt](https://github.com/sreedharjinka/Thyroid-DetectionG97/files/13238114/2-11-23.txt)
