### ISSUE TITLE
Plotting the correlation between the attreibutes using matplotlib and seaborn

### ISSUE THREAD

**Issue by sreedharjinka** [sreedharjinka/Thyroid-DetectionG97#9]

**Comment by pavitra-28** [comment]
using matplotlib and seaborn libraries completed plotting the correlation between TSH, T3, TT4, FTI using histogram and relation between age and the type of thyroid using scatter plot and a plot on counts of individual types of thyroid.
![Screenshot 2023-11-02 222634](https://github.com/sreedharjinka/Thyroid-DetectionG97/assets/139134167/c9268b9b-6f7e-4227-a0d9-011e7d0838d0)
![Screenshot 2023-11-02 222931](https://github.com/sreedharjinka/Thyroid-DetectionG97/assets/139134167/fc1aed72-bd81-4068-8607-67eb47a24604)
![Screenshot 2023-11-02 223407](https://github.com/sreedharjinka/Thyroid-DetectionG97/assets/139134167/4ee4c36e-d3e6-481c-8f9f-e54d71642360)
